// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181130110609_WillAddressEmail")]
    partial class WillAddressEmail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApplicationCore.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedUtc")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<bool>("Over18");

                    b.Property<DateTime>("UpdatedUtc")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("WillId");

                    b.HasKey("Id");

                    b.HasIndex("WillId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Will", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AddressId");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DOB");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedUtc")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique()
                        .HasFilter("[AddressId] IS NOT NULL");

                    b.ToTable("Wills");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Child", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Will", "Will")
                        .WithMany("Children")
                        .HasForeignKey("WillId");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Will", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Address", "Address")
                        .WithOne("Will")
                        .HasForeignKey("ApplicationCore.Entities.Will", "AddressId");
                });
#pragma warning restore 612, 618
        }
    }
}
